### ISSUE TITLE
Should be a bit more formal

### ISSUE THREAD

**Issue by Crowpik** [Lemrac/game-review-evaluation-sheet#1]
Example review:

Graphics:
☐ You forget what reality is
☐ Beautiful
☑ Good
☐ Decent
☐ Bad
☐ Don‘t look too long at it
☐ MS-DOS

Gameplay:
☐ Very good
☑ Good
☐ It‘s just gameplay
☐ Meh
☐ Watch paint dry instead
☐ Just don‘t

Audio:
☐ OH MY GOD
☑ Very good
☐ Good
☐ Not too bad
☐ Bad
☐ I'm now deaf

Audience:
☐ Kids
☐ Teens
☐ Adults
☑ All

PC Requirements:
☐ Check if you can run paint
☐ Potato
☐ Decent
☑ Fast
☐ Rich PC
☐ Ask NASA if they have a spare computer

Difficulty:
☐ Just press 'W'
☐ Easy
☐ Significant brain usage
☑ Easy to learn / Hard to master
☐ Difficult
☐ Dark Souls

---{Grind}---
☐ Nothing to grind
☐ Only if u care about leaderboards/ranks
☐ Isn't necessary to progress
☑ Average grind level
☐ Too much grind
☐ You‘ll need a second live for grinding

Story
☑ No story
☐ Some lore
☐ Average
☐ Good
☐ Lovely
☐ Better than real life

---{Game Time}---
☐ Long enough for a cup of coffee
☐ Short
☐ Average
☐ Long
☑ To infinity and beyond

Price:
☐ It’s free!
☐ Worth the price
☑ If you have some spare money left
☐ Not recommended
☐ You could also just burn your money

Bugs:
☐ Pretty much none
☐ Minor bugs
☑ Can get annoying
☐ ARK: Survival Evolved
☐ The game itself is a big terrarium for bugs

**Comment by Lemrac** [comment]
incorporated almost all of the suggestions, except for "OH MY GOD" (Audio) and "Rich PC" (PC Reqs)

**Comment by Crowpik** [comment]
Wow, I wasn't expecting you to reply, thanks!

**Comment by Lemrac** [comment]
tbh, i wasn't exptecting people to file issues, either :D
